// Product catalogue. No prices — showcase only (name, brand, image, description).
// Image paths point to /products/<slug>.jpg; UI falls back to a styled placeholder
// if the image is missing, so a broken download never breaks the page.

export type Product = {
  name: string;
  brand: string;
  desc: string;
  image: string; // /products/<slug>.jpg
};

export type Category = {
  key: string;
  label: string;
  blurb: string;
  products: Product[];
};

const img = (slug: string) => `/products/${slug}.jpg`;

export const CATEGORIES: Category[] = [
  {
    key: "laptops",
    label: "Laptops",
    blurb: "Student, business and gaming laptops from the brands you trust.",
    products: [
      { name: "Inspiron 15 3530", brand: "Dell", desc: "13th-gen Intel everyday laptop with a 15.6\" FHD display.", image: img("laptop-dell-inspiron-15") },
      { name: "Vostro 3520", brand: "Dell", desc: "Reliable business laptop built for long working days.", image: img("laptop-dell-vostro-3520") },
      { name: "Pavilion 14", brand: "HP", desc: "Slim 14\" all-rounder for home, study and light work.", image: img("laptop-hp-pavilion-14") },
      { name: "HP 15s", brand: "HP", desc: "Dependable budget laptop for browsing, classes and office apps.", image: img("laptop-hp-15s") },
      { name: "Victus 15 Gaming", brand: "HP", desc: "Entry gaming laptop with dedicated graphics and a fast panel.", image: img("laptop-hp-victus-15") },
      { name: "IdeaPad Slim 3", brand: "Lenovo", desc: "Lightweight 15\" laptop with all-day battery for students.", image: img("laptop-lenovo-ideapad-slim-3") },
      { name: "ThinkPad E14", brand: "Lenovo", desc: "Business-grade durability with a comfortable keyboard.", image: img("laptop-lenovo-thinkpad-e14") },
      { name: "LOQ 15 Gaming", brand: "Lenovo", desc: "Cool-running gaming laptop tuned for smooth frame-rates.", image: img("laptop-lenovo-loq-15") },
      { name: "Vivobook 15", brand: "ASUS", desc: "Colourful, slim 15.6\" laptop for everyday productivity.", image: img("laptop-asus-vivobook-15") },
      { name: "TUF Gaming F15", brand: "ASUS", desc: "Military-grade tough gaming laptop with a fast display.", image: img("laptop-asus-tuf-f15") },
      { name: "ROG Strix G16", brand: "ASUS", desc: "High-performance gaming laptop for serious players.", image: img("laptop-asus-rog-strix-g16") },
      { name: "Aspire 7", brand: "Acer", desc: "Big-screen laptop with graphics for work and casual gaming.", image: img("laptop-acer-aspire-7") },
      { name: "Aspire Lite", brand: "Acer", desc: "Thin and light everyday laptop at a friendly price.", image: img("laptop-acer-aspire-lite") },
      { name: "Nitro V 15", brand: "Acer", desc: "Gaming laptop with strong cooling and a high-refresh screen.", image: img("laptop-acer-nitro-v15") },
      { name: "Galaxy Book4", brand: "Samsung", desc: "Sleek, premium-feeling laptop with a bright display.", image: img("laptop-samsung-galaxy-book4") },
      { name: "Swift Go 14", brand: "Acer", desc: "Ultraportable with a crisp OLED-class panel for creators.", image: img("laptop-acer-swift-go-14") },
      { name: "Zenbook 14", brand: "ASUS", desc: "Premium ultrabook — light, fast and beautifully finished.", image: img("laptop-asus-zenbook-14") },
      { name: "ProBook 440", brand: "HP", desc: "Secure, manageable laptop for growing businesses.", image: img("laptop-hp-probook-440") },
      { name: "Yoga Slim 6", brand: "Lenovo", desc: "Elegant thin-and-light with a gorgeous display.", image: img("laptop-lenovo-yoga-slim-6") },
      { name: "XPS 13", brand: "Dell", desc: "Compact flagship ultrabook with a stunning edge-to-edge screen.", image: img("laptop-dell-xps-13") },
    ],
  },
  {
    key: "desktops",
    label: "Desktops",
    blurb: "Branded systems, all-in-ones and custom builds assembled in-store.",
    products: [
      { name: "Custom Home PC", brand: "SRS Build", desc: "Balanced desktop for browsing, study and office work.", image: img("desktop-srs-home") },
      { name: "Custom Office PC", brand: "SRS Build", desc: "Reliable everyday workstation specced to your budget.", image: img("desktop-srs-office") },
      { name: "Custom Gaming Rig", brand: "SRS Build", desc: "Built-to-order gaming PC with dedicated graphics.", image: img("desktop-srs-gaming") },
      { name: "Custom Workstation", brand: "SRS Build", desc: "High-core build for editing, CAD and heavy multitasking.", image: img("desktop-srs-workstation") },
      { name: "OptiPlex Tower", brand: "Dell", desc: "Business desktop known for stability and easy servicing.", image: img("desktop-dell-optiplex") },
      { name: "Vostro Tower", brand: "Dell", desc: "Affordable, dependable tower for small offices.", image: img("desktop-dell-vostro-tower") },
      { name: "Pavilion Desktop", brand: "HP", desc: "Family desktop with room to upgrade later.", image: img("desktop-hp-pavilion") },
      { name: "ProDesk SFF", brand: "HP", desc: "Space-saving small-form-factor PC for tidy desks.", image: img("desktop-hp-prodesk-sff") },
      { name: "All-in-One 24", brand: "HP", desc: "Clean, cable-free all-in-one with a 24\" display.", image: img("desktop-hp-aio-24") },
      { name: "IdeaCentre Tower", brand: "Lenovo", desc: "Roomy home desktop that's quiet and upgrade-friendly.", image: img("desktop-lenovo-ideacentre") },
      { name: "ThinkCentre SFF", brand: "Lenovo", desc: "Compact, secure business desktop.", image: img("desktop-lenovo-thinkcentre") },
      { name: "AIO 24 V-Series", brand: "Lenovo", desc: "All-in-one that keeps the desk neat and the setup simple.", image: img("desktop-lenovo-aio-24") },
      { name: "Aspire TC Tower", brand: "Acer", desc: "Value desktop tower for everyday family computing.", image: img("desktop-acer-aspire-tc") },
      { name: "Veriton SFF", brand: "Acer", desc: "Slim business desktop for offices short on space.", image: img("desktop-acer-veriton") },
      { name: "Mini PC", brand: "SRS Build", desc: "Tiny, low-power PC for reception desks and signage.", image: img("desktop-srs-mini") },
      { name: "Budget Student PC", brand: "SRS Build", desc: "Affordable first computer for online classes.", image: img("desktop-srs-student") },
      { name: "Creator PC", brand: "SRS Build", desc: "Colour-accurate build for photo and video editing.", image: img("desktop-srs-creator") },
      { name: "Streaming PC", brand: "SRS Build", desc: "Dual-purpose build for gaming and live streaming.", image: img("desktop-srs-streaming") },
      { name: "Shop Billing PC", brand: "SRS Build", desc: "Sturdy desktop set up for retail billing software.", image: img("desktop-srs-billing") },
      { name: "Server Tower", brand: "SRS Build", desc: "Entry server build for small-business file sharing.", image: img("desktop-srs-server") },
    ],
  },
  {
    key: "cctv",
    label: "CCTV & Security",
    blurb: "HD camera kits, DVR/NVR and full installation — brands we stock daily.",
    products: [
      { name: "ColorVu Bullet Camera", brand: "Hikvision", desc: "Full-colour night vision bullet camera for sharp 24/7 footage.", image: img("cctv-hikvision-colorvu-bullet") },
      { name: "Turbo HD Dome", brand: "Hikvision", desc: "Discreet indoor dome camera with two-way audio.", image: img("cctv-hikvision-turbo-dome") },
      { name: "Wi-Fi Home Camera", brand: "CP Plus", desc: "ezyKam+ Wi-Fi camera you can view from your phone.", image: img("cctv-cpplus-ezykam-wifi") },
      { name: "Dual Linkage Camera", brand: "COFE", desc: "Wi-Fi PTZ camera with AI and two-way talk.", image: img("cctv-cofe-dual-linkage") },
      { name: "3MP Wi-Fi Pan-Tilt", brand: "Trueview", desc: "All-time-colour mini pan-tilt camera, easy DIY setup.", image: img("cctv-trueview-wifi-pantilt") },
      { name: "3MP 4G Pan-Tilt", brand: "Trueview", desc: "4G SIM camera for sites without Wi-Fi.", image: img("cctv-trueview-4g-pantilt") },
      { name: "Wi-Fi Bullet Camera", brand: "Trueview", desc: "Weatherproof outdoor bullet camera with colour night view.", image: img("cctv-trueview-wifi-bullet") },
      { name: "Smart Bulb Camera", brand: "illumax", desc: "360° camera disguised as a light bulb for easy indoor cover.", image: img("cctv-illumax-bulb-camera") },
      { name: "4-Channel DVR", brand: "CP Plus", desc: "Records four cameras with remote phone playback.", image: img("cctv-cpplus-4ch-dvr") },
      { name: "8-Channel DVR", brand: "Hikvision", desc: "Eight-camera recorder for homes and shops.", image: img("cctv-hikvision-8ch-dvr") },
      { name: "4-Channel NVR", brand: "CP Plus", desc: "Network recorder for crisp IP-camera footage.", image: img("cctv-cpplus-4ch-nvr") },
      { name: "Surveillance HDD 1TB", brand: "WD Purple", desc: "Hard drive built for 24/7 CCTV recording.", image: img("cctv-wd-purple-1tb") },
      { name: "Surveillance HDD 2TB", brand: "Seagate SkyHawk", desc: "Higher-capacity drive for longer recording retention.", image: img("cctv-seagate-skyhawk-2tb") },
      { name: "4-Cam HD Kit", brand: "CP Plus", desc: "Complete kit: cameras, DVR, cabling and install.", image: img("cctv-cpplus-4cam-kit") },
      { name: "8-Cam HD Kit", brand: "Hikvision", desc: "Larger kit for shops and bigger premises.", image: img("cctv-hikvision-8cam-kit") },
      { name: "PoE IP Camera", brand: "Hikvision", desc: "Single-cable power + data IP camera for clean installs.", image: img("cctv-hikvision-poe-ip") },
      { name: "Solar Wi-Fi Camera", brand: "Trueview", desc: "Off-grid camera powered by its own solar panel.", image: img("cctv-trueview-solar") },
      { name: "Video Doorbell", brand: "CP Plus", desc: "See and speak to visitors from your phone.", image: img("cctv-cpplus-doorbell") },
      { name: "Two-Way Audio Camera", brand: "Hikvision", desc: "Built-in mic and speaker for live conversation.", image: img("cctv-hikvision-twoway") },
      { name: "Smart Camera 3-Pack", brand: "CP Plus", desc: "Value bundle of three Wi-Fi cameras for full home cover.", image: img("cctv-cpplus-smart-3pack") },
    ],
  },
  {
    key: "printers",
    label: "Printers & Ink",
    blurb: "Ink-tank, inkjet and laser printers plus genuine cartridges and ink.",
    products: [
      { name: "PIXMA G2012 Ink Tank", brand: "Canon", desc: "Refillable MegaTank printer with low running cost.", image: img("printer-canon-g2012") },
      { name: "PIXMA G3012 Wi-Fi", brand: "Canon", desc: "Wireless ink-tank all-in-one for home and office.", image: img("printer-canon-g3012") },
      { name: "PIXMA G3770", brand: "Canon", desc: "Fast, stylish Wi-Fi MegaTank with high page yield.", image: img("printer-canon-g3770") },
      { name: "EcoTank L3250", brand: "Epson", desc: "Compact Wi-Fi ink-tank for everyday printing.", image: img("printer-epson-l3250") },
      { name: "EcoTank L3210", brand: "Epson", desc: "Reliable all-in-one ink-tank with cartridge-free printing.", image: img("printer-epson-l3210") },
      { name: "EcoTank L5290", brand: "Epson", desc: "Ink-tank with ADF and fax for busy offices.", image: img("printer-epson-l5290") },
      { name: "LaserJet M141w", brand: "HP", desc: "Compact mono laser printer for crisp text.", image: img("printer-hp-laserjet-m141w") },
      { name: "LaserJet M236sdw", brand: "HP", desc: "Duplex laser all-in-one for small workgroups.", image: img("printer-hp-laserjet-m236") },
      { name: "Smart Tank 580", brand: "HP", desc: "Wireless ink-tank all-in-one with high yield.", image: img("printer-hp-smart-tank-580") },
      { name: "DCP-T426W", brand: "Brother", desc: "Wi-Fi ink-tank all-in-one that sips ink.", image: img("printer-brother-dcp-t426w") },
      { name: "HL-L2321D Laser", brand: "Brother", desc: "Fast duplex mono laser for high-volume text.", image: img("printer-brother-hl-l2321d") },
      { name: "GI-790 Black Ink", brand: "Canon", desc: "Genuine MegaTank refill ink, black.", image: img("ink-canon-gi-790") },
      { name: "003 Ink Bottle Set", brand: "Epson", desc: "Genuine EcoTank ink set (B/C/M/Y).", image: img("ink-epson-003-set") },
      { name: "001 Ink Bottle Set", brand: "Epson", desc: "Genuine ink set for compatible EcoTank models.", image: img("ink-epson-001-set") },
      { name: "GT53 Black Ink", brand: "HP", desc: "Genuine Smart Tank refill ink, black.", image: img("ink-hp-gt53") },
      { name: "BT5000 Colour Ink", brand: "Brother", desc: "Genuine refill ink for Brother ink-tank printers.", image: img("ink-brother-bt5000") },
      { name: "PG-47 / CL-57 Cartridge", brand: "Canon", desc: "Genuine cartridge pair for compatible PIXMA models.", image: img("ink-canon-pg47-cl57") },
      { name: "678 Cartridge", brand: "HP", desc: "Genuine black/colour cartridge for HP Deskjet.", image: img("ink-hp-678") },
      { name: "TN-2365 Toner", brand: "Brother", desc: "Genuine toner for Brother mono laser printers.", image: img("ink-brother-tn-2365") },
      { name: "88A Toner", brand: "HP", desc: "Genuine LaserJet toner for sharp, lasting prints.", image: img("ink-hp-88a-toner") },
    ],
  },
  {
    key: "networking",
    label: "Networking",
    blurb: "Routers, switches, range extenders and full small-office Wi-Fi.",
    products: [
      { name: "Archer C6 Router", brand: "TP-Link", desc: "Dual-band gigabit Wi-Fi router for busy homes.", image: img("net-tplink-archer-c6") },
      { name: "Archer AX23 Wi-Fi 6", brand: "TP-Link", desc: "Next-gen Wi-Fi 6 router for faster, smoother connections.", image: img("net-tplink-archer-ax23") },
      { name: "8-Port Gigabit Switch", brand: "TP-Link", desc: "Easy desktop switch to wire up more devices.", image: img("net-tplink-8port-switch") },
      { name: "5-Port Gigabit Switch", brand: "TP-Link", desc: "Compact switch for small office expansion.", image: img("net-tplink-5port-switch") },
      { name: "N300 Range Extender", brand: "TP-Link", desc: "Boosts Wi-Fi into dead corners of your home.", image: img("net-tplink-n300-extender") },
      { name: "AC1200 Range Extender", brand: "Tenda", desc: "Dual-band extender for wider, stronger coverage.", image: img("net-tenda-ac1200-extender") },
      { name: "Nova Mesh Wi-Fi", brand: "Tenda", desc: "Whole-home mesh system for seamless roaming.", image: img("net-tenda-nova-mesh") },
      { name: "DIR-615 Router", brand: "D-Link", desc: "Affordable Wi-Fi router for everyday browsing.", image: img("net-dlink-dir-615") },
      { name: "8-Port Switch", brand: "D-Link", desc: "Reliable unmanaged switch for home and office.", image: img("net-dlink-8port-switch") },
      { name: "USB Wi-Fi Adapter", brand: "TP-Link", desc: "Add fast wireless to any desktop in seconds.", image: img("net-tplink-usb-wifi") },
      { name: "Powerline Adapter Kit", brand: "TP-Link", desc: "Carries internet over your home's electrical wiring.", image: img("net-tplink-powerline") },
      { name: "4G LTE Router", brand: "TP-Link", desc: "SIM-based router for areas without wired broadband.", image: img("net-tplink-4g-router") },
      { name: "Outdoor Access Point", brand: "TP-Link", desc: "Extends Wi-Fi to gardens, yards and shopfronts.", image: img("net-tplink-outdoor-ap") },
      { name: "CAT6 LAN Cable (roll)", brand: "D-Link", desc: "High-speed network cabling for clean installations.", image: img("net-dlink-cat6-cable") },
      { name: "RJ45 Connectors Pack", brand: "D-Link", desc: "Connectors for terminating LAN cables neatly.", image: img("net-dlink-rj45") },
      { name: "Wi-Fi 6 Mesh 2-Pack", brand: "TP-Link", desc: "Deco mesh kit for fast, whole-home coverage.", image: img("net-tplink-deco-mesh") },
      { name: "Gigabit PoE Switch", brand: "TP-Link", desc: "Powers IP cameras and APs over the network cable.", image: img("net-tplink-poe-switch") },
      { name: "Network Patch Panel", brand: "D-Link", desc: "Keeps office cabling organised and serviceable.", image: img("net-dlink-patch-panel") },
      { name: "USB-LAN Adapter", brand: "TP-Link", desc: "Adds a wired port to laptops without ethernet.", image: img("net-tplink-usb-lan") },
      { name: "Dual-Band Nano Router", brand: "Tenda", desc: "Pocket router for travel and small spaces.", image: img("net-tenda-nano-router") },
    ],
  },
  {
    key: "storage",
    label: "Storage",
    blurb: "SSDs, hard drives, pen drives and memory cards for every need.",
    products: [
      { name: "Supersonic SSD 256GB", brand: "Geonix", desc: "Fast SATA SSD to revive any older laptop or PC.", image: img("storage-geonix-ssd-256") },
      { name: "SATA SSD 512GB", brand: "Foxin", desc: "Big, speedy SSD for everyday computing.", image: img("storage-foxin-ssd-512") },
      { name: "NVMe SSD 256GB", brand: "Crucial", desc: "Blazing M.2 NVMe drive for modern systems.", image: img("storage-crucial-nvme-256") },
      { name: "NVMe SSD 512GB", brand: "WD Blue", desc: "High-speed M.2 storage with strong endurance.", image: img("storage-wd-blue-nvme-512") },
      { name: "NVMe SSD 1TB", brand: "Crucial", desc: "Spacious, fast drive for games and creative work.", image: img("storage-crucial-nvme-1tb") },
      { name: "Internal HDD 1TB", brand: "Seagate", desc: "Trusted desktop hard drive for bulk storage.", image: img("storage-seagate-hdd-1tb") },
      { name: "Internal HDD 2TB", brand: "WD Blue", desc: "Roomy drive for photos, videos and backups.", image: img("storage-wd-blue-hdd-2tb") },
      { name: "Portable HDD 1TB", brand: "WD", desc: "Pocket hard drive to carry your files anywhere.", image: img("storage-wd-portable-1tb") },
      { name: "Portable HDD 2TB", brand: "Seagate", desc: "Slim external drive with generous capacity.", image: img("storage-seagate-portable-2tb") },
      { name: "Portable SSD 500GB", brand: "Samsung T7", desc: "Shock-resistant, ultra-fast external SSD.", image: img("storage-samsung-t7-500") },
      { name: "Pen Drive 32GB", brand: "SanDisk", desc: "Everyday USB drive for quick file transfers.", image: img("storage-sandisk-32gb") },
      { name: "Pen Drive 64GB", brand: "HP", desc: "Reliable USB 3.0 drive with metal body.", image: img("storage-hp-64gb") },
      { name: "Pen Drive 128GB", brand: "SanDisk", desc: "High-capacity USB drive for big files.", image: img("storage-sandisk-128gb") },
      { name: "microSD 64GB", brand: "SanDisk", desc: "Memory card for phones, cameras and dashcams.", image: img("storage-sandisk-microsd-64") },
      { name: "microSD 128GB", brand: "Samsung EVO", desc: "Fast, dependable card for 4K recording.", image: img("storage-samsung-evo-128") },
      { name: "Surveillance HDD 1TB", brand: "WD Purple", desc: "Built for continuous CCTV recording.", image: img("storage-wd-purple-1tb") },
      { name: "Surveillance HDD 2TB", brand: "Seagate SkyHawk", desc: "Higher capacity for longer CCTV retention.", image: img("storage-seagate-skyhawk-2tb") },
      { name: "SD Card Reader", brand: "Coconut", desc: "USB reader for SD and microSD cards.", image: img("storage-coconut-card-reader") },
      { name: "SSD Enclosure", brand: "Foxin", desc: "Turn a spare SSD into a fast portable drive.", image: img("storage-foxin-enclosure") },
      { name: "RAM 8GB DDR4", brand: "Crucial", desc: "Speed up your PC with a memory upgrade.", image: img("storage-crucial-ram-8gb") },
    ],
  },
  {
    key: "accessories",
    label: "Accessories",
    blurb: "Keyboards, mice, webcams, speakers, chargers, cables and more.",
    products: [
      { name: "Wireless Keyboard-Mouse Combo", brand: "Logitech", desc: "Clutter-free wireless combo for any desk.", image: img("acc-logitech-mk-combo") },
      { name: "Wired Keyboard", brand: "Zebronics", desc: "Comfortable everyday keyboard, built to last.", image: img("acc-zebronics-keyboard") },
      { name: "Wireless Mouse", brand: "Logitech", desc: "Smooth, reliable wireless mouse with long battery life.", image: img("acc-logitech-wireless-mouse") },
      { name: "Gaming Mouse", brand: "Fingers", desc: "RGB gaming mouse with adjustable sensitivity.", image: img("acc-fingers-gaming-mouse") },
      { name: "HD Webcam", brand: "Lapcare", desc: "Clear 1080p webcam for calls and classes.", image: img("acc-lapcare-webcam") },
      { name: "2.1 Speaker System", brand: "Fingers", desc: "Punchy desktop speakers with a dedicated subwoofer.", image: img("acc-fingers-speakers") },
      { name: "Over-Ear Headset", brand: "Zebronics", desc: "Comfortable headset with mic for calls and gaming.", image: img("acc-zebronics-headset") },
      { name: "30W USB-C Charger", brand: "Coconut", desc: "Fast charger for phones, tablets and accessories.", image: img("acc-coconut-30w-charger") },
      { name: "USB-C to USB-C Cable", brand: "Lapcare", desc: "Durable fast-charging cable that lasts.", image: img("acc-lapcare-usbc-cable") },
      { name: "Laptop Adapter (Universal)", brand: "Lapcare", desc: "Replacement charger for most laptop brands.", image: img("acc-lapcare-laptop-adapter") },
      { name: "Laptop Adapter", brand: "Zebion", desc: "High-performance replacement laptop adapter.", image: img("acc-zebion-adapter") },
      { name: "4-Port USB Hub", brand: "Coconut", desc: "Add more USB ports to any laptop or PC.", image: img("acc-coconut-usb-hub") },
      { name: "Laptop Bag", brand: "Lapcare", desc: "Padded backpack to carry your laptop safely.", image: img("acc-lapcare-bag") },
      { name: "Cooling Pad", brand: "Zebronics", desc: "Keeps your laptop cool during long sessions.", image: img("acc-zebronics-cooling-pad") },
      { name: "Laptop Stand", brand: "Lapcare", desc: "Raises your screen for better posture.", image: img("acc-lapcare-stand") },
      { name: "Mechanical Keyboard", brand: "Fingers", desc: "Tactile mechanical keys for typing and gaming.", image: img("acc-fingers-mech-keyboard") },
      { name: "Bluetooth Speaker", brand: "Zebronics", desc: "Portable speaker with rich, room-filling sound.", image: img("acc-zebronics-bt-speaker") },
      { name: "Wireless Earbuds", brand: "Fingers", desc: "True-wireless earbuds with a charging case.", image: img("acc-fingers-earbuds") },
      { name: "Screen Cleaning Kit", brand: "Coconut", desc: "Safely clean laptop and monitor screens.", image: img("acc-coconut-cleaning-kit") },
      { name: "HDMI Cable", brand: "Coconut", desc: "High-speed HDMI cable for crisp display output.", image: img("acc-coconut-hdmi") },
    ],
  },
  {
    key: "power",
    label: "UPS & Power",
    blurb: "UPS backup, inverters and stabilizers to keep you running.",
    products: [
      { name: "600VA UPS", brand: "APC", desc: "Keeps a single PC safe during short power cuts.", image: img("power-apc-600va") },
      { name: "1100VA UPS", brand: "APC", desc: "More backup for a PC plus monitor and peripherals.", image: img("power-apc-1100va") },
      { name: "Line-Interactive UPS", brand: "Zebronics", desc: "Affordable UPS with surge protection.", image: img("power-zebronics-ups") },
      { name: "600VA UPS", brand: "Microtek", desc: "Trusted backup for everyday desktop use.", image: img("power-microtek-600va") },
      { name: "Digital Inverter", brand: "Microtek", desc: "Reliable home inverter for longer outages.", image: img("power-microtek-inverter") },
      { name: "Sine-Wave Inverter", brand: "Luminous", desc: "Clean power for sensitive electronics.", image: img("power-luminous-inverter") },
      { name: "Inverter Battery", brand: "Luminous", desc: "Long-life battery to pair with your inverter.", image: img("power-luminous-battery") },
      { name: "TV Voltage Stabilizer", brand: "V-Guard", desc: "Protects your television from voltage swings.", image: img("power-vguard-tv-stabilizer") },
      { name: "AC Stabilizer", brand: "V-Guard", desc: "Keeps air-conditioners safe from fluctuations.", image: img("power-vguard-ac-stabilizer") },
      { name: "Fridge Stabilizer", brand: "Microtek", desc: "Voltage protection for your refrigerator.", image: img("power-microtek-fridge-stabilizer") },
      { name: "Spike Guard 6-Socket", brand: "GM", desc: "Surge-protected power strip for your desk.", image: img("power-gm-spike-guard") },
      { name: "Extension Board", brand: "GM", desc: "Multi-socket board with individual switches.", image: img("power-gm-extension") },
      { name: "Surge Protector", brand: "Belkin", desc: "Shields electronics from spikes and surges.", image: img("power-belkin-surge") },
      { name: "12V SMPS Power Supply", brand: "Zebronics", desc: "Efficient power supply for CCTV and DIY setups.", image: img("power-zebronics-smps") },
      { name: "Cabinet Cooling Fan", brand: "Fingers", desc: "12cm fan to keep cabinets and DVRs cool.", image: img("power-fingers-fan") },
      { name: "750VA UPS", brand: "iBall", desc: "Compact home UPS with steady backup.", image: img("power-iball-750va") },
      { name: "Online UPS 1KVA", brand: "APC", desc: "Always-on protection for critical systems.", image: img("power-apc-online-1kva") },
      { name: "Inverter Trolley", brand: "Luminous", desc: "Keeps your inverter and battery tidy and safe.", image: img("power-luminous-trolley") },
      { name: "Multi-Plug Adapter", brand: "GM", desc: "Universal adapter for mixed plug types.", image: img("power-gm-multiplug") },
      { name: "SMPS PC Power Supply", brand: "Zebronics", desc: "Reliable cabinet power supply for desktops.", image: img("power-zebronics-pc-smps") },
    ],
  },
];

export const CATEGORY_KEYS = CATEGORIES.map((c) => c.label);
